[tool.poetry]
name = "pythonicsql"
version = "0.1.0"
description = ""
authors = ["Rich Ramalho <richecr1799@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
databases = "^0.8.0"
pydantic = "^2.5.1"


[tool.poetry.group.dev.dependencies]
aiosqlite = "^0.19.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
